local h = require("tests.harness")
local config = require("shinsa.config")

h.test("config deep-merges defaults without mutating caller options", function()
  config._reset()
  local opts = { panel = { width = 48 }, handoff = { git = false } }
  local result = config.setup(opts)
  h.eq(48, result.panel.width)
  h.eq("left", result.panel.side)
  h.eq(false, result.handoff.git)
  h.eq("auto", result.handoff.diff)
  result.panel.width = 80
  h.eq(48, opts.panel.width)
end)

h.test("config rejects invalid values with a precise path", function()
  config._reset()
  h.raises("panel.side", function()
    config.setup({ panel = { side = "middle" } })
  end)
  h.raises("git_command", function()
    config.setup({ git_command = {} })
  end)
  h.raises("handoff.diff", function()
    config.setup({ handoff = { diff = "unknown" } })
  end)
end)

h.test("invalid reconfiguration does not replace valid config", function()
  config._reset()
  config.setup({ panel = { width = 52 } })
  h.raises("panel.width", function()
    config.setup({ panel = { width = 10 } })
  end)
  h.eq(52, config.get().panel.width)
end)
