require("tests.config_spec")
require("tests.diff_parser_spec")
require("tests.git_spec")
require("tests.analyzer_spec")
require("tests.symbols_spec")
require("tests.rank_spec")
require("tests.ledger_spec")
require("tests.ui_spec")
require("tests.integrations_spec")
require("tests.plugin_spec")

require("tests.harness").finish()
