[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=--export=__externref_table_alloc",
    "-C", "link-arg=--export=__externref_table_dealloc",
    "-C", "link-arg=--export=__externref_drop_slice",
]
