pub use design_gate_core::{BlindSpot, BlindSpotManifest};

pub(crate) fn build(
    parse_failures: usize,
    metadata_failed: bool,
    edition_fallback_2024: bool,
    git_churn_failed: bool,
    coverage_approximated: bool,
    llvm_cov_unmatched: bool,
) -> BlindSpotManifest {
    let mut notes = vec![
        "No type resolution or macro expansion: calls and Result returns are matched syntactically."
            .to_string(),
        "Churn is file-grained: every function in the same file receives the same git history score."
            .to_string(),
        "Coverage reachability scans src/, tests/, benches/, and examples/ test functions, but remains syntactic."
            .to_string(),
        "Bare-name coverage matching is only a fallback when a production function name is unambiguous; qualified Type::method names are preferred."
            .to_string(),
        "Issue keys intentionally exclude churn, complexity, and coverage buckets so baseline ratchets stay stable when scores cross thresholds."
            .to_string(),
        "Git history is path based; complex rename/copy histories may be undercounted."
            .to_string(),
    ];
    let mut notes_ja = vec![
        "型解決とマクロ展開は行いません: 呼び出しと Result 返却は構文的に照合します。".to_string(),
        "churn はファイル粒度です。同じファイル内の全関数は同じ git 履歴スコアになります。".to_string(),
        "coverage 到達性は src/、tests/、benches/、examples/ のテスト関数を走査しますが、構文的な近似です。".to_string(),
        "coverage の bare 名一致は production 関数名が一意な場合のフォールバックに限定し、Type::method の qualified name を優先します。".to_string(),
        "baseline ratchet の安定性のため、Issue key には churn・complexity・coverage のバケットを含めません。".to_string(),
        "git 履歴は path ベースです。複雑な rename/copy 履歴は過少計上される可能性があります。".to_string(),
    ];
    if metadata_failed {
        notes.push(
            "cargo metadata failed; package metadata dependent output may be approximate."
                .to_string(),
        );
        notes_ja.push(
            "cargo metadata に失敗したため、package metadata に依存する出力は近似です。"
                .to_string(),
        );
    }
    if edition_fallback_2024 {
        notes.push(
            "Cargo edition could not be read; sources were parsed as Edition2024.".to_string(),
        );
        notes_ja.push(
            "Cargo edition を読み取れなかったため、Edition2024 としてパースしました。".to_string(),
        );
    }
    if git_churn_failed {
        notes.push("git log history could not be used for at least one file; churn fell back to a conservative approximation.".to_string());
        notes_ja.push("一部ファイルで git log 履歴を利用できず、churn は保守的な近似値にフォールバックしました。".to_string());
    }
    if coverage_approximated {
        notes.push(
            "No llvm-cov JSON was provided; coverage is approximated from test-call reachability."
                .to_string(),
        );
        notes_ja.push("llvm-cov JSON が指定されていないため、coverage はテスト呼び出し到達性から近似しています。".to_string());
    }
    if llvm_cov_unmatched {
        notes.push("Provided llvm-cov JSON did not match any production function; check paths and schema shape before trusting 0% coverage.".to_string());
        notes_ja.push("指定された llvm-cov JSON が production 関数に 1 件も一致しませんでした。0% coverage を信頼する前に path と schema 形状を確認してください。".to_string());
    }
    if parse_failures > 0 {
        notes.push(format!(
            "{parse_failures} Rust source file(s) could not be parsed cleanly."
        ));
        notes_ja.push(format!(
            "{parse_failures} 件の Rust ソースを完全には解析できませんでした。"
        ));
    }
    BlindSpotManifest {
        blind_spots: vec![
            BlindSpot {
                id: "macro-generated-code".to_string(),
                description: "Functions, branches, or tests generated by macros are not expanded.".to_string(),
                description_ja: "マクロ生成された関数・分岐・テストは展開しません。".to_string(),
            },
            BlindSpot {
                id: "coverage-approximation".to_string(),
                description: "Without llvm-cov JSON, dynamic execution coverage is approximated by syntactic reachability from tests in src/, tests/, benches/, and examples/.".to_string(),
                description_ja: "llvm-cov JSON なしでは、動的実行 coverage は src/、tests/、benches/、examples/ のテストからの構文的到達性で近似します。".to_string(),
            },
            BlindSpot {
                id: "rename-history".to_string(),
                description: "Path-based git history may miss complex rename, copy, or file split histories.".to_string(),
                description_ja: "path ベースの git 履歴は複雑な rename・copy・file split 履歴を取りこぼす可能性があります。".to_string(),
            },
            BlindSpot {
                id: "file-grained-churn".to_string(),
                description: "Churn is collected per file, not per function.".to_string(),
                description_ja: "churn は関数単位ではなくファイル単位で集計します。".to_string(),
            },
            BlindSpot {
                id: "llvm-cov-schema-matching".to_string(),
                description: "llvm-cov JSON support expects function entries with names, filenames, and count/region data; unmatched valid-looking JSON is reported as approximate.".to_string(),
                description_ja: "llvm-cov JSON は name・filenames・count/regions を持つ function entry を前提にします。一致しない正常形 JSON は近似として報告します。".to_string(),
            },
        ],
        notes,
        notes_ja,
    }
}
