use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::specialty::SpecialtyWithProficiency;

/// Engineer entity with game mechanics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Engineer {
    pub id: Uuid,
    /// Level (1-100)
    pub level: i32,
    /// Experience points
    pub xp: i64,
    /// XP needed for next level
    pub xp_to_next_level: i64,
    /// Satisfaction score (0-100) - affects productivity and retention
    pub satisfaction: i32,
    /// Monthly salary
    pub salary: i64,
    /// Total revenue generated by this engineer
    pub total_revenue: i64,
    /// Number of completed projects
    pub completed_projects: i32,
    /// Number of resolved incidents
    pub resolved_incidents: i32,
    /// Is the engineer currently active (not fired)
    pub is_active: bool,
    pub hired_at: DateTime<Utc>,
    pub fired_at: Option<DateTime<Utc>>,
}

impl Engineer {
    /// Calculate XP needed for a given level
    pub fn xp_for_level(level: i32) -> i64 {
        // Exponential growth: 100 * 1.5^(level-1)
        (100.0 * 1.5_f64.powi(level - 1)) as i64
    }

    /// Check if engineer can level up
    pub fn can_level_up(&self) -> bool {
        self.xp >= self.xp_to_next_level && self.level < 100
    }

    /// Level up the engineer
    pub fn level_up(&mut self) {
        if self.can_level_up() {
            self.xp -= self.xp_to_next_level;
            self.level += 1;
            self.xp_to_next_level = Self::xp_for_level(self.level + 1);
        }
    }
}

/// Engineer row from database (email is in public.users, not engineers table)
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct EngineerRow {
    pub id: Uuid,
    pub level: i32,
    pub xp: i64,
    pub xp_to_next_level: i64,
    pub satisfaction: i32,
    pub salary: i64,
    pub total_revenue: i64,
    pub completed_projects: i32,
    pub resolved_incidents: i32,
    pub is_active: bool,
    pub hired_at: DateTime<Utc>,
    pub fired_at: Option<DateTime<Utc>>,
}

impl From<EngineerRow> for Engineer {
    fn from(row: EngineerRow) -> Self {
        Self {
            id: row.id,
            level: row.level,
            xp: row.xp,
            xp_to_next_level: row.xp_to_next_level,
            satisfaction: row.satisfaction,
            salary: row.salary,
            total_revenue: row.total_revenue,
            completed_projects: row.completed_projects,
            resolved_incidents: row.resolved_incidents,
            is_active: row.is_active,
            hired_at: row.hired_at,
            fired_at: row.fired_at,
        }
    }
}

/// Engineer with specialties for API response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineerWithSpecialties {
    pub id: Uuid,
    pub email: String,
    /// Level shown to all
    pub level: i32,
    /// XP shown to all
    pub xp: i64,
    pub xp_to_next_level: i64,
    /// Satisfaction shown to all
    pub satisfaction: i32,
    /// Salary - only shown to managers
    #[serde(skip_serializing_if = "Option::is_none")]
    pub salary: Option<i64>,
    /// Stats hidden from non-managers
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_revenue: Option<i64>,
    pub completed_projects: i32,
    pub resolved_incidents: i32,
    pub is_active: bool,
    /// Specialties - proficiency hidden from non-managers
    pub specialties: Vec<SpecialtyWithProficiency>,
    /// Current workload (number of active assignments)
    pub active_assignments: i32,
}

/// Case/Project difficulty level (1-5)
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Difficulty {
    /// Easy - suitable for beginners
    Easy = 1,
    /// Normal - suitable for intermediate
    #[default]
    Normal = 2,
    /// Hard - requires intermediate+
    Hard = 3,
    /// Expert - requires expert level
    Expert = 4,
    /// Extreme - requires multiple experts
    Extreme = 5,
}

impl Difficulty {
    pub fn level(&self) -> i32 {
        *self as i32
    }

    /// Calculate satisfaction change based on engineer skill vs difficulty match
    /// Returns negative if difficulty is too high, positive if good match
    pub fn satisfaction_impact(&self, engineer_skill: i32) -> i32 {
        let diff = engineer_skill - self.level();
        match diff {
            // Perfect match or slightly challenging
            0 | -1 => 10,
            // Slightly below skill level (boring)
            1 => 0,
            // Way below skill level (very boring)
            2.. => -5,
            // Too difficult
            -2 => -10,
            // Way too difficult
            _ => -20,
        }
    }
}

impl std::fmt::Display for Difficulty {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Difficulty::Easy => write!(f, "easy"),
            Difficulty::Normal => write!(f, "normal"),
            Difficulty::Hard => write!(f, "hard"),
            Difficulty::Expert => write!(f, "expert"),
            Difficulty::Extreme => write!(f, "extreme"),
        }
    }
}

impl std::str::FromStr for Difficulty {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "easy" | "1" => Ok(Difficulty::Easy),
            "normal" | "2" => Ok(Difficulty::Normal),
            "hard" | "3" => Ok(Difficulty::Hard),
            "expert" | "4" => Ok(Difficulty::Expert),
            "extreme" | "5" => Ok(Difficulty::Extreme),
            _ => Err(format!("Invalid difficulty: {}", s)),
        }
    }
}

/// Revenue entry for tracking engineer contributions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RevenueEntry {
    pub id: Uuid,
    pub engineer_id: Uuid,
    pub project_id: Option<Uuid>,
    pub incident_id: Option<Uuid>,
    pub amount: i64,
    pub description: String,
    pub created_at: DateTime<Utc>,
}

/// Tenant revenue summary
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TenantRevenue {
    pub total_revenue: i64,
    pub monthly_revenue: i64,
    pub required_revenue: i64,
    /// If revenue falls below this, must fire engineers
    pub is_at_risk: bool,
}

/// Request to update engineer satisfaction
#[derive(Debug, Deserialize)]
pub struct UpdateSatisfactionRequest {
    pub satisfaction_delta: i32,
    pub reason: String,
}

/// Request to fire an engineer
#[derive(Debug, Deserialize)]
pub struct FireEngineerRequest {
    pub reason: String,
}

/// Request to add revenue
#[derive(Debug, Deserialize)]
pub struct AddRevenueRequest {
    pub amount: i64,
    pub description: String,
    pub project_id: Option<Uuid>,
    pub incident_id: Option<Uuid>,
}
