use std::fmt::Write as _;

use crate::cli::OutputFormat;
use crate::error::Result;
use crate::metadata::{DependencySummary, ProjectAnalysis};
use crate::sibling::{SiblingReport, SiblingStatus};
use crate::source::{ModuleSummary, SourceAnalysis};

pub fn render(
    project: &ProjectAnalysis,
    source: &SourceAnalysis,
    risks: &[SiblingReport],
    format: OutputFormat,
    japanese: bool,
) -> Result<String> {
    let mut out = String::new();
    match format {
        OutputFormat::Markdown => {}
        OutputFormat::AgentsMd => {
            writeln!(out, "# AGENTS.md")?;
            writeln!(out)?;
            writeln!(out, "Generated by `cargo agent-context`.")?;
            writeln!(out)?;
        }
        OutputFormat::ClaudeMd => {
            writeln!(out, "# CLAUDE.md")?;
            writeln!(out)?;
            writeln!(out, "Generated by `cargo agent-context`.")?;
            writeln!(out)?;
        }
    }
    if japanese {
        render_japanese(project, source, risks, &mut out)?;
    } else {
        render_english(project, source, risks, &mut out)?;
    }
    Ok(out)
}

fn render_english(
    project: &ProjectAnalysis,
    source: &SourceAnalysis,
    risks: &[SiblingReport],
    out: &mut String,
) -> Result<()> {
    writeln!(out, "# Rust Agent Context: {}", project.name)?;
    writeln!(out)?;
    render_overview(project, out)?;
    render_module_graph(project, source, out)?;
    render_public_api(source, out)?;
    render_build_commands(project, out)?;
    render_known_risks(risks, out)?;
    render_blind_spots(risks, out)?;
    render_conventions(project, out)?;
    Ok(())
}

fn render_japanese(
    project: &ProjectAnalysis,
    source: &SourceAnalysis,
    risks: &[SiblingReport],
    out: &mut String,
) -> Result<()> {
    writeln!(out, "# Rust Agent Context: {}", project.name)?;
    writeln!(out)?;
    render_overview(project, out)?;
    render_module_graph(project, source, out)?;
    render_public_api(source, out)?;
    render_build_commands(project, out)?;
    render_known_risks(risks, out)?;
    render_blind_spots(risks, out)?;
    render_conventions(project, out)?;
    Ok(())
}

fn render_overview(project: &ProjectAnalysis, out: &mut String) -> Result<()> {
    writeln!(out, "## Overview")?;
    writeln!(out)?;
    writeln!(out, "- Crate: `{}`", project.name)?;
    writeln!(out, "- Edition: `{}`", project.edition)?;
    writeln!(out, "- Type: `{}`", project.crate_kind.as_str())?;
    writeln!(
        out,
        "- Manifest: `{}`",
        design_gate_core::relative_path_string(&project.root, &project.manifest_path)
    )?;
    writeln!(
        out,
        "- Dependencies: {}",
        dependency_line(&project.dependencies)
    )?;
    if project.workspace_members.len() > 1 {
        writeln!(
            out,
            "- Workspace members: {}",
            project.workspace_members.join(", ")
        )?;
        writeln!(
            out,
            "- Note: workspace roots are summarized at member level; pass an individual crate path for per-crate module and API analysis."
        )?;
    }
    writeln!(out)?;
    Ok(())
}

fn render_module_graph(
    project: &ProjectAnalysis,
    source: &SourceAnalysis,
    out: &mut String,
) -> Result<()> {
    writeln!(out, "## Module graph")?;
    writeln!(out)?;
    if project.workspace_members.len() > 1 {
        writeln!(
            out,
            "Workspace root detected. Members: {}.",
            project.workspace_members.join(", ")
        )?;
        writeln!(
            out,
            "Per-crate module analysis is intentionally omitted at the workspace root; run this tool against a member crate."
        )?;
        writeln!(out)?;
        return Ok(());
    }
    if source.module_graph.is_empty() {
        writeln!(out, "No Rust modules were found under `src/`.")?;
        writeln!(out)?;
        return Ok(());
    }
    writeln!(
        out,
        "Rust files parsed: {}. Parse errors observed: {}.",
        source.files_analyzed, source.parse_errors
    )?;
    writeln!(out)?;
    for module in &source.module_graph {
        render_module(module, 0, out)?;
    }
    writeln!(out)?;
    Ok(())
}

fn render_module(module: &ModuleSummary, depth: usize, out: &mut String) -> Result<()> {
    let indent = "  ".repeat(depth);
    writeln!(
        out,
        "{}- `{}`: {} public item(s){}",
        indent,
        module.path,
        module.pub_item_count,
        type_suffix(&module.major_types)
    )?;
    for child in &module.children {
        render_module(child, depth + 1, out)?;
    }
    Ok(())
}

fn render_public_api(source: &SourceAnalysis, out: &mut String) -> Result<()> {
    writeln!(out, "## Key types & public API")?;
    writeln!(out)?;
    if source.public_api.is_empty() {
        writeln!(
            out,
            "No public `struct`, `enum`, `trait`, or free `fn` items were found."
        )?;
        writeln!(out)?;
        return Ok(());
    }
    writeln!(
        out,
        "| Module | Kind | Name | Signature | Location | Fan-in |"
    )?;
    writeln!(out, "|---|---:|---|---|---|---:|")?;
    for item in &source.public_api {
        writeln!(
            out,
            "| `{}` | {} | `{}` | `{}` | `{}`:{} | {} |",
            escape_table(&item.module),
            item.kind,
            escape_table(&item.name),
            escape_table(&item.signature),
            escape_table(&item.file),
            item.line,
            item.fan_in
        )?;
    }
    if source.total_public_api > source.public_api.len() {
        writeln!(
            out,
            "\nShowing top {} of {} public API items by fan-in and stable name order.",
            source.public_api.len(),
            source.total_public_api
        )?;
    } else {
        writeln!(
            out,
            "\nTotal public API items: {}.",
            source.total_public_api
        )?;
    }
    writeln!(out)?;
    Ok(())
}

fn render_build_commands(project: &ProjectAnalysis, out: &mut String) -> Result<()> {
    writeln!(out, "## Build & test commands")?;
    writeln!(out)?;
    if project.build_commands.is_empty() {
        writeln!(
            out,
            "No verified Cargo commands were inferred from repository files."
        )?;
    } else {
        for command in &project.build_commands {
            writeln!(out, "- `{}`: {}", command.command, command.reason)?;
        }
    }
    writeln!(out)?;
    Ok(())
}

fn render_known_risks(risks: &[SiblingReport], out: &mut String) -> Result<()> {
    writeln!(out, "## Known risks")?;
    writeln!(out)?;
    if risks.len() == 1
        && risks[0].tool == "sibling-tools"
        && risks[0]
            .blind_spots
            .iter()
            .any(|spot| spot == "no sibling tools available")
    {
        writeln!(out, "no sibling tools available")?;
        writeln!(out)?;
        return Ok(());
    }
    writeln!(out, "| Tool | Status | Grade | Issues | Top issues |")?;
    writeln!(out, "|---|---|---:|---:|---|")?;
    for risk in risks {
        writeln!(
            out,
            "| `{}` | {} | {} | {} | {} |",
            risk.tool,
            status_text(&risk.status),
            risk.grade.as_deref().unwrap_or("-"),
            risk.issue_count
                .map(|count| count.to_string())
                .unwrap_or_else(|| "-".to_string()),
            top_issues_text(risk)
        )?;
    }
    writeln!(out)?;
    Ok(())
}

fn render_blind_spots(risks: &[SiblingReport], out: &mut String) -> Result<()> {
    writeln!(out, "## Blind spots & caveats")?;
    writeln!(out)?;
    writeln!(
        out,
        "- `cargo-agent-context` uses syntax-only CST parsing; macro-generated APIs and proc-macro expansion are not resolved."
    )?;
    writeln!(
        out,
        "- cfg branches are not evaluated. Items under `#[cfg(test)]` are excluded, but other target-specific APIs may be summarized together."
    )?;
    writeln!(
        out,
        "- Workspace roots list members and conventions; run against each member crate for per-crate API context."
    )?;
    let mut printed = false;
    for risk in risks {
        for spot in &risk.blind_spots {
            if !printed {
                writeln!(out, "- Integrated sibling blind spots:")?;
                printed = true;
            }
            writeln!(out, "  - `{}`: {}", risk.tool, spot)?;
        }
    }
    writeln!(out)?;
    Ok(())
}

fn render_conventions(project: &ProjectAnalysis, out: &mut String) -> Result<()> {
    writeln!(out, "## Conventions")?;
    writeln!(out)?;
    if project.conventions.is_empty() {
        writeln!(
            out,
            "No `rustfmt.toml`, `clippy.toml`, `deny.toml`, `CLAUDE.md`, or `AGENTS.md` files were found at the target root."
        )?;
        writeln!(out)?;
        return Ok(());
    }
    for convention in &project.conventions {
        writeln!(out, "- `{}`: {}", convention.path, convention.summary)?;
    }
    writeln!(out)?;
    Ok(())
}

fn dependency_line(summary: &DependencySummary) -> String {
    format!(
        "normal {} [{}], dev {} [{}], build {} [{}]",
        summary.normal.len(),
        preview(&summary.normal),
        summary.dev.len(),
        preview(&summary.dev),
        summary.build.len(),
        preview(&summary.build)
    )
}

fn preview(items: &[String]) -> String {
    if items.is_empty() {
        return "-".to_string();
    }
    let mut shown = items.iter().take(8).cloned().collect::<Vec<_>>();
    if items.len() > shown.len() {
        shown.push(format!("+{} more", items.len() - shown.len()));
    }
    shown.join(", ")
}

fn type_suffix(types: &[String]) -> String {
    if types.is_empty() {
        String::new()
    } else {
        format!("; major types: {}", types.join(", "))
    }
}

fn status_text(status: &SiblingStatus) -> String {
    match status {
        SiblingStatus::Loaded => "loaded".to_string(),
        SiblingStatus::Ran => "ran".to_string(),
        SiblingStatus::NotProvided => "not provided".to_string(),
        SiblingStatus::NotRun => "not run".to_string(),
        SiblingStatus::RunFailed(reason) => format!("run failed: {}", escape_table(reason)),
        SiblingStatus::SchemaMismatch(reason) => {
            format!("schema mismatch: {}", escape_table(reason))
        }
    }
}

fn top_issues_text(report: &SiblingReport) -> String {
    if report.top_issues.is_empty() {
        return "-".to_string();
    }
    report
        .top_issues
        .iter()
        .map(|issue| {
            format!(
                "{} {} at {}: {}",
                issue.severity, issue.kind, issue.location, issue.message
            )
        })
        .map(|text| escape_table(&text))
        .collect::<Vec<_>>()
        .join("<br>")
}

fn escape_table(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}
