pub use design_gate_core::{BlindSpot, BlindSpotManifest};

pub(crate) fn build(
    parse_failures: usize,
    metadata_failed: bool,
    edition_fallback_2024: bool,
    bare_name_fallback: bool,
) -> BlindSpotManifest {
    let mut notes = vec![
        "No type resolution: aliases and re-exported error types are matched syntactically."
            .to_string(),
        "Public trait impl reachability is approximate: impl blocks are treated as public when their text mentions a public trait or public type.".to_string(),
        "error-enum-bloat only checks variant count; unrelated domain mixing inside an enum is not implemented.".to_string(),
    ];
    let mut notes_ja = vec![
        "型解決は行いません: type alias や re-export されたエラー型は構文的に照合します。"
            .to_string(),
        "pub trait / impl の到達性は近似です: impl ブロック本文が pub trait または pub 型名に触れている場合に public とみなします。".to_string(),
        "error-enum-bloat は variant 数のみを検査します。無関係ドメイン混在の検出は未実装です。".to_string(),
    ];
    if metadata_failed {
        notes.push(
            "cargo metadata failed; package metadata dependent output may be approximate."
                .to_string(),
        );
        notes_ja.push(
            "cargo metadata に失敗したため、package metadata に依存する出力は近似です。"
                .to_string(),
        );
    }
    if edition_fallback_2024 {
        notes.push(
            "Cargo edition could not be read; sources were parsed as Edition2024.".to_string(),
        );
        notes_ja.push(
            "Cargo edition を読み取れなかったため、Edition2024 としてパースしました。".to_string(),
        );
    }
    if bare_name_fallback {
        notes.push(
            "Call graph used bare-name fallback after same-file and same-module resolution failed."
                .to_string(),
        );
        notes_ja.push("呼び出しグラフで同一ファイル・同一モジュール解決に失敗した箇所は bare name fallback を使いました。".to_string());
    }
    if parse_failures > 0 {
        notes.push(format!(
            "{parse_failures} Rust source file(s) could not be parsed cleanly."
        ));
        notes_ja.push(format!(
            "{parse_failures} 件の Rust ソースを完全には解析できませんでした。"
        ));
    }
    BlindSpotManifest {
        blind_spots: vec![
            BlindSpot {
                id: "macro-generated-code".to_string(),
                description: "Error paths generated by macros are not expanded and may be missing from the graph.".to_string(),
                description_ja: "マクロ生成されたエラー経路は展開しないため、グラフから漏れる可能性があります。".to_string(),
            },
            BlindSpot {
                id: "trait-and-dynamic-dispatch".to_string(),
                description: "Trait calls, dyn dispatch, and callback-driven control flow are not resolved.".to_string(),
                description_ja: "trait 呼び出し、dyn dispatch、コールバック経由の制御フローは解決しません。".to_string(),
            },
            BlindSpot {
                id: "cfg-and-generated-sources".to_string(),
                description: "Inactive cfg branches and build-script generated files are not analyzed unless present as source files.".to_string(),
                description_ja: "無効な cfg 分岐と build script 生成ファイルは、ソースとして存在しない限り解析しません。".to_string(),
            },
        ],
        notes,
        notes_ja,
    }
}
