// poseSpecs.js
// ポーズを「関節角」だけでなく、柔術の読み取りに必要な身体制約として定義する。
// _audit と validate-data がこの仕様を読み、重心・支持基底・接触・力の方向を確認する。

import { POSE_SPEC_ROLES } from "./positionCatalog.js";

const S = ({
  role,
  base,
  radius,
  offset = [0, 0],
  load = "self",
  contacts,
  force,
  vector = [0, 0],
  note = "",
}) => ({
  role,
  support: { base, radius, offset, load },
  contacts,
  force,
  vector,
  note,
});

export const POSE_SPECS = {
  standingRed: S({
    role: "standing",
    base: "feet",
    radius: 0.24,
    contacts: ["両足"],
    force: "礼・開始姿勢",
    note: "赤は青へ向いて立つ",
  }),
  standingBlue: S({
    role: "standing",
    base: "feet",
    radius: 0.24,
    contacts: ["両足"],
    force: "礼・開始姿勢",
    note: "青は赤へ向いて立つ",
  }),

  blueSeatedFront: S({
    role: "seated-front",
    base: "seat-feet",
    radius: 0.32,
    contacts: ["尻", "両足"],
    force: "首を守る前の座位",
    note: "赤に背中を取られている",
  }),
  redBackControl: S({
    role: "back-control-top",
    base: "seat-hooks",
    radius: 0.34,
    offset: [0, -0.02],
    load: "opponent-back",
    contacts: ["胸-背中", "両脚フック", "シートベルト"],
    force: "背中を密着し首へ圧",
    vector: [0, 0.16],
    note: "青の背中側から同方向を向く",
  }),
  blueBackDefend: S({
    role: "back-defense-bottom",
    base: "seat-feet",
    radius: 0.34,
    contacts: ["防御手", "尻", "足裏"],
    force: "顎を引き弱い側へ腰を抜く",
    vector: [-0.14, 0.08],
  }),
  blueTapped: S({
    role: "submitted-bottom",
    base: "seat-feet",
    radius: 0.32,
    contacts: ["首", "タップ手"],
    force: "首を守れずタップ",
    vector: [0, 0.1],
  }),

  blueUnderMount: S({
    role: "supine-bottom",
    base: "back-feet",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor-opponent",
    contacts: ["背中", "腰", "肘"],
    force: "下から橋の準備",
    vector: [0, -0.08],
  }),
  redMountTop: S({
    role: "mount-top",
    base: "knees-opponent-torso",
    radius: 0.34,
    load: "opponent-torso",
    contacts: ["両膝-腰横", "骨盤-中心線", "手のベース"],
    force: "骨盤を中心線へ落とす",
    vector: [0, 0.1],
  }),
  redMountArmbar: S({
    role: "mount-top-attacking-arm",
    base: "knees-opponent-torso",
    radius: 0.34,
    load: "opponent-torso",
    contacts: ["膝-腰横", "胸圧", "腕隔離"],
    force: "胸圧で肘を体から剥がす",
    vector: [-0.08, 0.12],
  }),
  blueUpaTop: S({
    role: "guard-top-after-sweep",
    base: "knees-hands",
    radius: 0.34,
    load: "self",
    contacts: ["両膝", "手のベース", "相手の腰"],
    force: "上を取り返してベースを作る",
    vector: [0, 0.1],
  }),
  redRolledBottom: S({
    role: "supine-bottom",
    base: "back-feet",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor",
    contacts: ["背中", "膝", "防御手"],
    force: "返されて下になる",
  }),

  redClosedGuardBottom: S({
    role: "closed-guard-bottom",
    base: "back-hips",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor",
    contacts: ["背中", "脚-腰回り", "袖/手首"],
    force: "脚で腰を囲み姿勢を崩す",
    vector: [0, -0.12],
  }),
  blueTopInGuard: S({
    role: "closed-guard-top",
    base: "knees-feet",
    radius: 0.34,
    load: "self",
    contacts: ["両膝", "腰のベース", "胸/襟制御"],
    force: "背筋を立て肘を内へ戻す",
    vector: [0, 0.12],
  }),
  blueGuardPass: S({
    role: "guard-pass-top",
    base: "knees-feet",
    radius: 0.42,
    offset: [0.04, -0.06],
    load: "self-opponent-hip",
    contacts: ["膝の楔", "腰制御", "手のベース"],
    force: "腰を制して横へ回る",
    vector: [-0.12, 0.18],
  }),
  redGuardOpened: S({
    role: "open-guard-bottom",
    base: "back-feet",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor",
    contacts: ["背中", "開いた脚", "フレーム"],
    force: "ガードを開かれ距離を作る",
  }),

  redSideControl: S({
    role: "side-control-top",
    base: "knees-toes-opponent-chest",
    radius: 0.42,
    offset: [0, -0.02],
    load: "opponent-chest",
    contacts: ["胸-胸", "肩圧", "腰制御", "膝/爪先"],
    force: "胸と肩で横から潰す",
    vector: [-0.16, 0.02],
  }),
  blueUnderSide: S({
    role: "side-control-bottom",
    base: "back-frames",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor-opponent",
    contacts: ["背中", "首フレーム", "腰フレーム"],
    force: "フレームで空間を作る",
    vector: [-0.16, -0.04],
  }),
  blueShrimpRecover: S({
    role: "shrimp-bottom",
    base: "side-hip-feet",
    radius: 0.4,
    offset: [-0.06, 0.02],
    load: "floor",
    contacts: ["肩", "腰", "差し込む膝"],
    force: "腰を逃がして膝を戻す",
    vector: [-0.22, -0.04],
  }),
  blueSideControl: S({
    role: "side-control-top",
    base: "knees-toes-opponent-chest",
    radius: 0.42,
    offset: [0, -0.02],
    load: "opponent-chest",
    contacts: ["胸-胸", "肩圧", "腰制御", "膝/爪先"],
    force: "胸と肩で横から潰す",
    vector: [-0.16, 0.02],
  }),
  redUnderSide: S({
    role: "side-control-bottom",
    base: "back-frames",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor-opponent",
    contacts: ["背中", "首フレーム", "腰フレーム"],
    force: "下でフレームを作る",
    vector: [-0.16, -0.04],
  }),
  blueClimbToMount: S({
    role: "mount-top",
    base: "knees-opponent-torso",
    radius: 0.34,
    load: "opponent-torso",
    contacts: ["両膝-腰横", "骨盤-中心線", "手のベース"],
    force: "位置を上げてマウントへ",
    vector: [0, 0.1],
  }),
  redUnderMount: S({
    role: "supine-bottom",
    base: "back-feet",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor-opponent",
    contacts: ["背中", "腰", "肘"],
    force: "マウント下で肘を守る",
  }),

  blueIsolateArm: S({
    role: "mount-top-attacking-arm",
    base: "knees-opponent-torso",
    radius: 0.34,
    load: "opponent-torso",
    contacts: ["胸圧", "肘隔離", "膝-腰横"],
    force: "腕を中心線から外す",
    vector: [0.04, 0.1],
  }),
  redArmIsolated: S({
    role: "supine-bottom-arm-isolated",
    base: "back-feet",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor-opponent",
    contacts: ["背中", "孤立した腕"],
    force: "肘を戻せず防御が薄い",
  }),
  blueArmbarFinish: S({
    role: "armbar-attacker",
    base: "hips-legs",
    radius: 0.38,
    load: "self-opponent-arm",
    contacts: ["股関節-肩", "脚-頭/胸", "両手-手首"],
    force: "腰を伸ばして肘を制御",
    vector: [-0.12, -0.16],
  }),
  redArmbarCaught: S({
    role: "armbar-defender",
    base: "back-shoulders",
    radius: 0.38,
    offset: [0, 0.04],
    load: "floor",
    contacts: ["背中", "伸ばされる腕"],
    force: "肘が支点へ向く危険",
  }),

  redGuardArmbarFinish: S({
    role: "guard-armbar-attacker",
    base: "back-hips-angle",
    radius: 0.4,
    offset: [-0.04, 0.04],
    load: "floor-opponent-arm",
    contacts: ["脚-顔/背中", "腰角度", "手首制御"],
    force: "角度を切って肘を伸ばす",
    vector: [0.2, -0.08],
  }),
  blueGuardArmbarCaught: S({
    role: "guard-armbar-defender",
    base: "knees-hands-compromised",
    radius: 0.34,
    load: "self-opponent-leg",
    contacts: ["片腕", "頭を下げた姿勢", "膝のベース"],
    force: "姿勢を折られ片腕が外れる",
    vector: [-0.14, 0.04],
  }),

  blueGivesBack: S({
    role: "prone-bottom",
    base: "knees-elbows",
    radius: 0.34,
    load: "floor-opponent",
    contacts: ["膝", "肘", "背中を見せる"],
    force: "背中を向けて首を晒す",
    vector: [0, 0.12],
  }),
  redTriangleFinish: S({
    role: "triangle-attacker",
    base: "back-hips-angle",
    radius: 0.4,
    offset: [-0.04, 0.04],
    load: "floor-opponent-neck",
    contacts: ["脚ロック", "首", "片腕", "腰角度"],
    force: "脚で首と肩を閉じる",
    vector: [0.16, -0.12],
  }),
  blueCaughtInTriangle: S({
    role: "triangle-defender",
    base: "knees-hands-compromised",
    radius: 0.34,
    load: "self-opponent-leg",
    contacts: ["首", "片腕", "崩れた姿勢"],
    force: "頭を下げられ片腕が中に残る",
    vector: [-0.1, 0.1],
  }),
};

export { POSE_SPEC_ROLES };
